## Association Rule Mining Using Apriori Algorithm

In [1]:
pip install mlxtend

Requirement already satisfied: mlxtend in /opt/anaconda3/lib/python3.12/site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: numpy>=2.3.5 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (2.5.3)
Requirement already satisfied: pandas>=2.3.3 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (3.0.6)
Requirement already satisfied: scikit-learn>=1.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (3.11.2)
Requirement already satisfied: joblib>=1.5.2 in /opt/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from joblib>=1.5.2->mlxtend) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (23.2)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.16.0)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.8.0->mlxtend) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
data = pd.read_csv('/Users/kimheang/Documents/Learning 2/python-for-data-science-and-machine-learning-essential-training-part-2-3016934/data/groceries.csv')

In [4]:
data.head()

                  1                    2               3  ...    7    8    9
0      citrus fruit  semi-finished bread       margarine  ...  NaN  NaN  NaN
1    tropical fruit               yogurt          coffee  ...  NaN  NaN  NaN
2        whole milk                  NaN             NaN  ...  NaN  NaN  NaN
3         pip fruit               yogurt   cream cheese   ...  NaN  NaN  NaN
4  other vegetables           whole milk  condensed milk  ...  NaN  NaN  NaN

[5 rows x 9 columns]

In [ ]:
basket_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [6]:
basket_sets.head()

   Instant food products  UHT-milk  ...  yogurt  zwieback
0                      0         0  ...       0         0
1                      0         0  ...       1         0
2                      0         0  ...       0         0
3                      0         0  ...       1         0
4                      0         0  ...       0         0

[5 rows x 165 columns]

In [8]:
basket_sets_bool = basket_sets.astype(bool)
apriori(basket_sets_bool, min_support=0.02)

      support                    itemsets
0    0.028155              frozenset({1})
1    0.054369              frozenset({8})
2    0.032039              frozenset({9})
3    0.027508             frozenset({10})
4    0.072492             frozenset({11})
..        ...                         ...
105  0.022977       frozenset({154, 163})
106  0.033981       frozenset({162, 158})
107  0.055987       frozenset({162, 163})
108  0.022977  frozenset({121, 162, 101})
109  0.022977  frozenset({162, 163, 101})

[110 rows x 2 columns]

In [9]:
basket_sets_bool = basket_sets.astype(bool)
apriori(basket_sets_bool, min_support=0.02, use_colnames=True)

      support                                           itemsets
0    0.028155                              frozenset({UHT-milk})
1    0.054369                                  frozenset({beef})
2    0.032039                               frozenset({berries})
3    0.027508                             frozenset({beverages})
4    0.072492                          frozenset({bottled beer})
..        ...                                                ...
105  0.022977                frozenset({tropical fruit, yogurt})
106  0.033981        frozenset({whipped/sour cream, whole milk})
107  0.055987                    frozenset({yogurt, whole milk})
108  0.022977  frozenset({other vegetables, root vegetables, ...
109  0.022977  frozenset({other vegetables, yogurt, whole milk})

[110 rows x 2 columns]

In [10]:
df_combo = basket_sets.astype(bool)
frequent_itemsets=apriori(df_combo, min_support=0.002, use_colnames=True)
frequent_itemsets['Length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

       support                                           itemsets  Length
0     0.007120                 frozenset({Instant food products})       1
1     0.028155                              frozenset({UHT-milk})       1
2     0.002913                      frozenset({abrasive cleaner})       1
3     0.003560                      frozenset({artif. sweetener})       1
4     0.014887                         frozenset({baking powder})       1
...        ...                                                ...     ...
2313  0.002265  frozenset({other vegetables, root vegetables, ...       5
2314  0.002589  frozenset({other vegetables, yogurt, whipped/s...       5
2315  0.002265  frozenset({other vegetables, pip fruit, yogurt...       5
2316  0.002265  frozenset({other vegetables, root vegetables, ...       5
2317  0.002265  frozenset({other vegetables, yogurt, whipped/s...       5

[2318 rows x 3 columns]

In [11]:
frequent_itemsets[(frequent_itemsets['Length']>=3)]

       support                                           itemsets  Length
1260  0.002589  frozenset({UHT-milk, other vegetables, bottled...       3
1261  0.002265         frozenset({UHT-milk, soda, bottled water})       3
1262  0.002589  frozenset({baking powder, other vegetables, wh...       3
1263  0.002265  frozenset({baking powder, whipped/sour cream, ...       3
1264  0.002589             frozenset({whole milk, berries, beef})       3
...        ...                                                ...     ...
2313  0.002265  frozenset({other vegetables, root vegetables, ...       5
2314  0.002589  frozenset({other vegetables, yogurt, whipped/s...       5
2315  0.002265  frozenset({other vegetables, pip fruit, yogurt...       5
2316  0.002265  frozenset({other vegetables, root vegetables, ...       5
2317  0.002265  frozenset({other vegetables, yogurt, whipped/s...       5

[1058 rows x 3 columns]

In [12]:
rule = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.9)
rule.head()

                                   antecedents  ... kulczynski
0            frozenset({hamburger meat, curd})  ...   0.506305
1    frozenset({root vegetables, frozen fish})  ...   0.504414
2    frozenset({sausage, soda, bottled water})  ...   0.466366
3  frozenset({sausage, yogurt, bottled water})  ...   0.464708
4   frozenset({butter, pip fruit, whole milk})  ...   0.462949

[5 rows x 14 columns]

In [13]:
rule = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rule.head()

                          antecedents  ... kulczynski
0  frozenset({Instant food products})  ...   0.164973
1       frozenset({other vegetables})  ...   0.164973
2  frozenset({Instant food products})  ...   0.169385
3        frozenset({root vegetables})  ...   0.169385
4               frozenset({UHT-milk})  ...   0.143844

[5 rows x 14 columns]

In [15]:
rule[(rule['lift']>=5 & (rule['confidence']>=0.8))]

                             antecedents  ... kulczynski
0     frozenset({Instant food products})  ...   0.164973
1          frozenset({other vegetables})  ...   0.164973
2     frozenset({Instant food products})  ...   0.169385
3           frozenset({root vegetables})  ...   0.169385
4                  frozenset({UHT-milk})  ...   0.143844
...                                  ...  ...        ...
9413       frozenset({other vegetables})  ...   0.275113
9414                 frozenset({yogurt})  ...   0.299941
9415     frozenset({whipped/sour cream})  ...   0.190625
9416         frozenset({tropical fruit})  ...   0.217396
9417             frozenset({whole milk})  ...   0.354414

[9418 rows x 14 columns]